### ISSUE TITLE
Bug on Recent Release

### ISSUE THREAD

**Issue by ToonTamilIndia** [TechShreyash/AnimeDexLite#1]
In ~~most popular~~ Recent Release if we choose any anime like beyblade x it has 10 episodes released 
The link redirect https://animedex.pages.dev/anime?anime=beyblade-x-episode-10
But the actual url https://animedex.pages.dev/anime?anime=beyblade-x

Please fix it

**Comment by TechShreyash** [comment]
@ToonTamilIndia Most popular section in home page ?

**Comment by ToonTamilIndia** [comment]
> @ToonTamilIndia Most popular section in home page ?

ya yes and i am used your script on http://www.toontamilind.in/          

and sorry it's not most popular its  Recent Release

**Comment by TechShreyash** [comment]
@ToonTamilIndia Oh yeah i saw the problem

Will fix it soon

**Comment by ToonTamilIndia** [comment]
> @ToonTamilIndia Oh yeah i saw the problem
> 
> Will fix it soon

Thank you

**Comment by TechShreyash** [comment]
Fixed...

You can check on main site https://animedex.pages.dev

Check recent commit https://github.com/TechShreyash/AnimeDexLite/commit/f6f5a4a620482a47041d5fdadad0dc20a2e07714
