### ISSUE TITLE
Unresponsive on mobile

### ISSUE THREAD

**Issue by DevHelio** [TechShreyash/AnimeDexLite#2]
The website is currently not really mobile friendly. Although you can find your way through, it still doesn't give you that mobile feel.

🫡 I am currently working on this and I'm excited to show results!

**Comment by TechShreyash** [comment]
> The website is currently not really mobile friendly. Although you can find your way through, it still doesn't give you that mobile feel.

AnimeDex was my first website i made, so didnt have much experience and also it was the first time i used html css to create a website

thats why it looks like thats

> 🫡 I am currently working on this and I'm excited to show results!

Great to know, i will be waiting to see it
