### ISSUE TITLE
videos not playing

### ISSUE THREAD

**Issue by ammystic** [TechShreyash/AnimeDexLite#25]
![image](https://github.com/TechShreyash/AnimeDexLite/assets/150622366/eb08c681-e606-4dfa-94b5-fa2592fcc075)
![image](https://github.com/TechShreyash/AnimeDexLite/assets/150622366/050baa63-bcab-4a0e-aa7f-6621055f5987)

Error
As you can see there are no episodes on any animedex site and therefore they are not playing anything.
How To Reproduce
Try to watch an anime

**Comment by TechShreyash** [comment]
Fixed in latest version, Try now
