### ISSUE TITLE
Web not working 

### ISSUE THREAD

**Issue by Varun0236** [TechShreyash/AnimeDexLite#29]
It's still not working it s
Keep saying something went wrong or something

**Comment by sudeep3127y** [comment]
https://litestream.pages.dev/ ise this

**Comment by TechShreyash** [comment]
> https://litestream.pages.dev/ ise this

Everything working fine

**Comment by TechShreyash** [comment]
Provide screenshot and page url

**Comment by Varun0236** [comment]
Hi thanks for the link of new website

**Comment by TechShreyash** [comment]
Main website : animedex.pages.dev will always work
