### ISSUE TITLE
Website not opening 😔😔

### ISSUE THREAD

**Issue by AKATSUKI3979** [TechShreyash/AnimeDexLite#31]
WHILE TODAY I WAS DOWNLOADING NARUTO IN ENGLISH SUB IT SHOWS ME A ERROR EVERYTIME THAT OOPS SOMETHING WENT WRONG PLEASE HELP😔😔

**Comment by sudeep3127y** [comment]
Use this
https://litestream.pages.dev/

**Comment by TechShreyash** [comment]
@AKATSUKI3979 Give link of page

**Comment by TechShreyash** [comment]
@sudeep3127y I warn you not to send your website's url again
