### ISSUE TITLE
Keep chabging the api link

### ISSUE THREAD

**Issue by Jeroscie** [TechShreyash/AnimeDexLite#33]
Why you guys keep changing the api link?

**Comment by TechShreyash** [comment]
@Jeroscie where api is deployed, cloudflare only allows 100k requests per day

the public api which i deployed was reaching  the max usage and thereafter stops working
Screenshots : https://telegram.me/TechZBots/764

i dont want my site to be down, as it is using same api

so its a simple solution, i will keep changing api domains so only my website will be able to use
or if new people forks a repo, they will have new code with new api so they can test

**Comment by anime-dex** [comment]
if you want to use, you can always deploy a copy of animedex api on cloudflare for free

**Comment by Jeroscie** [comment]
Alright cool thanks
