### ISSUE TITLE
Comments...

### ISSUE THREAD

**Issue by CUZAMARK** [TechShreyash/AnimeDexLite#34]
Hey dude, can you add Disqus comments system?

**Comment by TechShreyash** [comment]
@CUZAMARK yes

**Comment by TechShreyash** [comment]
they show ads on website on free plan, so cant add it

**Comment by CUZAMARK** [comment]
Just a recommendation, if possible you can add "COMMENTS" button like GOGOANIME uses.

**Comment by AuraMoon55** [comment]
@CUZAMARK Check Disqus
They are easy af to add if you want in your clone

**Comment by CUZAMARK** [comment]
Ohk, nvm.
