### ISSUE TITLE
Video player not working on ios (apple) devices

### ISSUE THREAD

**Issue by DevHelio** [TechShreyash/AnimeDexLite#4]
The video player does not go on fullscreen mode and you gotta be lucky for any video to play.

**Comment by ToonTamilIndia** [comment]
> The video player does not go on fullscreen mode and you gotta be lucky for any video to play.

 http://www.toontamilind.in/ created from animedexlite here i use art player and jw player I cannot guarantee its compatibility with iOS devices please give it a try and let me know if it works

**Comment by DevHelio** [comment]
> > The video player does not go on fullscreen mode and you gotta be lucky for any video to play.
> 
> 
> 
>  http://www.toontamilind.in/ created from animedexlite here i use art player and jw player I cannot guarantee its compatibility with iOS devices please give it a try and let me know if it works

Are there any other players? Where'd you get yours?

**Comment by ToonTamilIndia** [comment]
> > > The video player does not go on fullscreen mode and you gotta be lucky for any video to play.
> > 
> > 
> > http://www.toontamilind.in/ created from animedexlite here i use art player and jw player I cannot guarantee its compatibility with iOS devices please give it a try and let me know if it works
> 
> Are there any other players? Where'd you get yours?

I does not understand clearly, I think You want the art player or js player code 
art player official web : https://artplayer.org/                                                                           there customize your player as you want

**Comment by TechShreyash** [comment]
try using now if it works after this commit https://github.com/TechShreyash/AnimeDexLite/commit/040ed9c9002fca9ad2240a1a40cf2b79a838ff2f
