### ISSUE TITLE
anime recomendation thumbnail not showing

### ISSUE THREAD

**Issue by NEWBIENOOB-0** [TechShreyash/AnimeDexLite#5]
[https://animedex.pages.dev/anime?anime=dungeon-meshi](url) scroll it and image is not loading fetching through api simailar page not working
![image](https://github.com/TechShreyash/AnimeDexLite/assets/54370549/bfb49c40-1124-4d15-a624-a49369caa970)

**Comment by TechShreyash** [comment]
thanks for reporting, the issue is fixed now
